[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=6144"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
