export { default as FcaOverviewImage } from "./FcaOverviewImage.svg";
export { default as img1FcaApplicationImage } from "./img1FcaApplicationImage.svg";
export { default as img2FcaApplicationImage } from "./img2FcaApplicationImage.svg";
export { default as img3FcaApplicationImage } from "./img3FcaApplicationImage.svg";
export { default as img4FcaApplicationImage } from "./img4FcaApplicationImage.svg";
export { default as img1PaymentServicesNewAuthorisationRegistrationImage } from "./img1FcaApplicationImage.svg";  //del
export { default as img2PaymentServicesNewAuthorisationRegistrationImage } from "./img1FcaApplicationImage.svg";  //del
export { default as img3PaymentServicesNewAuthorisationRegistrationImage } from "./img1FcaApplicationImage.svg"; //dele
export { default as img1EMoneyNewAuthorisationRegistrationImage } from "./img1EMoneyNewAuthorisationRegistrationImage.svg";
export { default as img2EMoneyNewAuthorisationRegistrationImage } from "./img2EMoneyNewAuthorisationRegistrationImage.svg";
// export { default as FcaApplicationPageImage1 } from "./FcaApplicationPageImage1.svg";
// export { default as FcaApplicationPageImage2 } from "./FcaApplicationPageImage2.svg";
// export { default as FcaApplicationPageImage3 } from "./FcaApplicationPageImage3.svg";
// export { default as FcaApplicationPageImage4 } from "./FcaApplicationPageImage4.svg";
export { default as SemiImag0 } from "./SemiImage0.svg";
export { default as SemiImage1 } from "./SemiImage1.svg";
export { default as SemiImage2 } from "./SemiImage2.svg";
export { default as SemiImage3 } from "./SemiImage3.svg";
export { default as SemiImage4 } from "./SemiImage4.svg";
export { default as SemiImage5 } from "./SemiImage5.svg";
export { default as SemiImage6 } from "./SemiImage6.svg";
export { default as SemiImage7 } from "./SemiImage7.svg";
export { default as SemiImage8 } from "./SemiImage8.svg";
export { default as SemiImage9 } from "./SemiImage9.svg";
export { default as SemiImage10 } from "./SemiImage10.svg";
export { default as SemiImage11 } from "./SemiImage11.svg";
export { default as SemiImage12 } from "./SemiImage12.svg";
export { default as SemiImage13 } from "./SemiImage13.svg";
export { default as SemiImage14 } from "./SemiImage14.svg";
export { default as SemiImage15 } from "./SemiImage15.svg";
export { default as SemiImage16 } from "./SemiImage16.svg";
export { default as SemiImage17 } from "./SemiImage17.svg";
export { default as SemiImage18 } from "./SemiImage18.svg";
export { default as SemiImage19 } from "./SemiImage19.svg";
export { default as SemiImage20 } from "./SemiImage20.svg";
export { default as SemiImage21 } from "./SemiImage21.svg";
// export { default as SemiImage22 } from "./SemiImage22.svg";
export { default as IdentificationDetailsAndTimingsImage } from "./IdentificationDetailsAndTimingsImage.svg";
export { default as IdentificationDetailsAndTimings1Image } from "./IdentificationDetailsAndTimings1Image.svg";
export { default as IdentificationDetailsAndTimings2Image } from "./IdentificationDetailsAndTimings2Image.svg";
export { default as IdentificationDetailsAndTimings3Image } from "./IdentificationDetailsAndTimings3Image.svg";
export { default as SemiImage } from "./SemiImage.svg";
export { default as ConditionsForRegistration2Image } from "./ConditionsForRegistration2Image.svg";
export { default as ConditionsForRegistration1Image } from "./ConditionsForRegistration1Image.svg";
export { default as BusinessPlanImage } from "./BusinessPlanImage.svg";
export { default as CapitalResourcesAndRequirementsImage } from "./CapitalResourcesAndRequirementsImage.svg";
export { default as CapitalResourcesAndRequirements1Image } from "./CapitalResourcesAndRequirements1Image.svg";
export { default as CapitalResourcesAndRequirements2Image } from "./CapitalResourcesAndRequirements2Image.svg";
export { default as SafeguardingMeasuresImage } from "./SafeguardingMeasuresImage.svg";
export { default as UnrelatedPaymentServicesImage } from "./UnrelatedPaymentServicesImage.svg";
export { default as GovernanceArrangementsAndRiskManagementImage } from "./GovernanceArrangementsAndRiskManagementImage.svg";
export { default as QualifyingHoldingsAndCloseLinksImage } from "./QualifyingHoldingsAndCloseLinksImage.svg";
export { default as ProcedureToMonitorHandleAndFollowUpOnSecurityIncidentsAndCustomerComplaintsImage } from "./ProcedureToMonitorHandleAndFollowUpOnSecurityIncidentsAndCustomerComplaintsImage.svg";
export { default as ProcessInPlaceToFileMonitorTrackAndRestrictAccessToSensitivePaymentDataImage } from "./ProcessInPlaceToFileMonitorTrackAndRestrictAccessToSensitivePaymentDataImage.svg";
export { default as ThePrinciplesAndDefinitionsApplicableToTheCollectionOfStatisticalDataOnPerformanceTransactionsAndFraudImage } from "./ThePrinciplesAndDefinitionsApplicableToTheCollectionOfStatisticalDataOnPerformanceTransactionsAndFraudImage.svg";
export { default as SecurityPolicyImage } from "./SecurityPolicyImage.svg";
export { default as FeesAndLeviesImage } from "./FeesAndLeviesImage.svg";
