export { default as FcaOverviewImage } from "./FcaOverviewImage.svg";
export { default as img1FcaApplicationImage } from "./img1FcaApplicationImage.svg";
export { default as img2FcaApplicationImage } from "./img2FcaApplicationImage.svg";
export { default as img3FcaApplicationImage } from "./img3FcaApplicationImage.svg";
export { default as img4FcaApplicationImage } from "./img4FcaApplicationImage.svg";
// export { default as FcaApplicationPageImage1 } from "./FcaApplicationPageImage1.svg";
// export { default as FcaApplicationPageImage2 } from "./FcaApplicationPageImage2.svg";
// export { default as FcaApplicationPageImage3 } from "./FcaApplicationPageImage3.svg";
// export { default as FcaApplicationPageImage4 } from "./FcaApplicationPageImage4.svg";
export { default as PispApiTermsInApplicationPackImage } from "./PispApiTermsInApplicationPackImage.svg";
export { default as PispApiSection3BusinessPlanImage } from "./PispApiSection3BusinessPlanImage.svg";
export { default as PispApiSection4StructuralOrganisationImage } from "./PispApiSection4StructuralOrganisationImage.svg";
export { default as PispApiSection5EvidenceOfInitialCapitalImage } from "./PispApiSection5EvidenceOfInitialCapitalImage.svg";
export { default as PispApiSection8ProcedureToMonitorHandleAndFollowUpOnASecurityIncidentAndSecurityRelatedCustomerComplaintsImage } from "./PispApiSection8ProcedureToMonitorHandleAndFollowUpOnASecurityIncidentAndSecurityRelatedCustomerComplaintsImage.svg";
export { default as PispApiSection14Image } from "./PispApiSection14Image.svg";
export { default as PispApiSection15Image } from "./PispApiSection15Image.svg";
export { default as PispApiSection18FeesAndLeviesImage } from "./PispApiSection18FeesAndLeviesImage.svg";
export { default as PispApiFillingInTheFormImage } from "./PispApiFillingInTheFormImage.svg";
export { default as PispApiSection6MeasuresToSafeguardTheFundsOfPaymentServiceUsersImage } from "./PispApiSection6MeasuresToSafeguardTheFundsOfPaymentServiceUsersImage.svg";
export { default as PispApiSection7ProcedureToMonitorHandleAndFollowUpOnASecurityIncidentAndSecurityRelatedCustomerComplaintsImage } from "./PispApiSection7ProcedureToMonitorHandleAndFollowUpOnASecurityIncidentAndSecurityRelatedCustomerComplaintsImage.svg";
export { default as PispApiThePrinciplesAndDefinitionsApplicableToTheCollectionOfStatisticalDataOnPerformanceTransactionsAndFraudImage } from "./PispApiThePrinciplesAndDefinitionsApplicableToTheCollectionOfStatisticalDataOnPerformanceTransactionsAndFraudImage.svg";
export { default as PispApiSection1IdentificationDetailsAndTimingsImage } from "./PispApiSection1IdentificationDetailsAndTimingsImage.svg";
export { default as PispApiProcessInPlaceToFileMonitorTrackAndRestrictAccessToSensitivePaymentDataImage } from "./PispApiProcessInPlaceToFileMonitorTrackAndRestrictAccessToSensitivePaymentDataImage.svg";
export { default as PispApiSecurityPolicyDocumentImage } from "./PispApiSecurityPolicyDocumentImage.svg";
export { default as PispApiSection16ProfessionalIndemnityInsurancePiiOrComparableGuaranteeImage } from "./PispApiSection16ProfessionalIndemnityInsurancePiiOrComparableGuaranteeImage.svg";
export { default as PispApiSection2ProgrammeOfOperationsImage } from "./PispApiSection2ProgrammeOfOperationsImage.svg";
export { default as PispApiBusinessContinuityArrangementsImage } from "./PispApiBusinessContinuityArrangementsImage.svg";
export { default as PpispApiInternalControlMechanismsToComplyWithObligationsInRelationToMoneyLaunderingAndTerroristFinancingImage } from "./PpispApiInternalControlMechanismsToComplyWithObligationsInRelationToMoneyLaunderingAndTerroristFinancingImage.svg";
export { default as PispApiSection17ProfessionalIndemnityInsurancePiiOrComparableGuaranteeImage } from "./PispApiSection17ProfessionalIndemnityInsurancePiiOrComparableGuaranteeImage.svg";
